---
title: "Car Explorer Presentation"
author: "Thomas Jaensch"
date: "6/28/2017"
output: ioslides_presentation
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Summary

Car Explorer demo app that lets the user select the make, class, and year in R's ggplot's "mpg" dataset and display the selection results in an HTML table.

## App

```{r, echo = FALSE}
library(ggplot2)
library(shiny)
shinyApp(
  
  ui = fluidPage(
  titlePanel("Car Explorer Demo App, June 28, 2017"),
  
  # Create a new Row in the UI for selectInputs
  fluidRow(
    column(4,
           selectInput("man",
                       "Make:",
                       c("All",
                         unique(as.character(mpg$manufacturer))))
    ),
    column(4,
           selectInput("class",
                       "Class:",
                       c("All",
                         unique(as.character(mpg$class))))
    ),
    column(4,
           selectInput("year",
                       "Year:",
                       c("All",
                         unique(as.character(mpg$year))))
    )
  ),
  # Create a new row for the table.
  fluidRow(
    DT::dataTableOutput("table")
  )
),
  
  server = function(input, output) {
  
  # Filter data based on selections
  output$table <- DT::renderDataTable(DT::datatable({
    data <- mpg
    if (input$man != "All") {
      data <- data[data$manufacturer == input$man,]
    }
    if (input$class != "All") {
      data <- data[data$class == input$class,]
    }
    if (input$year != "All") {
      data <- data[data$year == input$year,]
    }
    data
  }))
  
},
  
  options = list(height = 500)
)
```

## UI code

```{r, echo = TRUE, eval = FALSE}
# Load ggplot2 package which provides 'mpg' dataset.
library(ggplot2)
fluidPage(
  titlePanel("Car Explorer Demo App, June 28, 2017"),
  # Create a new Row in the UI for selectInputs
  fluidRow(
    column(4,
           selectInput("man",
                       "Make:",
                       c("All",
                         unique(as.character(mpg$manufacturer))))
    ),
    column(4,
           selectInput("class",
                       "Class:",
                       c("All",
                         unique(as.character(mpg$class))))
    ),
    column(4,
           selectInput("year",
                       "Year:",
                       c("All",
                         unique(as.character(mpg$year))))
    )
  ),
  # Create a new row for the table.
  fluidRow(
    DT::dataTableOutput("table")
  )
)
```

## Server code

```{r, echo = TRUE, eval = FALSE}
library(ggplot2)
function(input, output) {
  # Filter data based on selections
  output$table <- DT::renderDataTable(DT::datatable({
    data <- mpg
    if (input$man != "All") {
      data <- data[data$manufacturer == input$man,]
    }
    if (input$class != "All") {
      data <- data[data$class == input$class,]
    }
    if (input$year != "All") {
      data <- data[data$year == input$year,]
    }
    data
  }))
  
}
```